export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  TEACHER = 'TEACHER',
  STUDENT = 'STUDENT',
}

export enum QuizStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum QuizSessionMode {
  LIVE_GROUP = 'LIVE_GROUP',
  INDIVIDUAL = 'INDIVIDUAL',
}

export enum SessionStatus {
  PENDING = 'PENDING',
  WAITING_PARTICIPANTS = 'WAITING_PARTICIPANTS',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum QuestionType {
  SINGLE_CHOICE = 'SINGLE_CHOICE',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
}

export enum IssueSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
}

export enum IssueType {
  MISSING_CORRECT_ANSWER = 'MISSING_CORRECT_ANSWER',
  MULTIPLE_CORRECT_ANSWERS = 'MULTIPLE_CORRECT_ANSWERS',
  TOO_FEW_OPTIONS = 'TOO_FEW_OPTIONS',
  TOO_MANY_OPTIONS = 'TOO_MANY_OPTIONS',
  EMPTY_QUESTION_TEXT = 'EMPTY_QUESTION_TEXT',
  EMPTY_OPTION_TEXT = 'EMPTY_OPTION_TEXT',
  DUPLICATE_OPTION = 'DUPLICATE_OPTION',
  DUPLICATE_QUESTION = 'DUPLICATE_QUESTION',
  QUESTION_TEXT_TOO_LONG = 'QUESTION_TEXT_TOO_LONG',
  OPTION_TEXT_TOO_LONG = 'OPTION_TEXT_TOO_LONG',
  UNSUPPORTED_FORMULA = 'UNSUPPORTED_FORMULA',
  IMAGE_EXTRACTION_FAILED = 'IMAGE_EXTRACTION_FAILED',
}

export enum AssetType {
  QUESTION_IMAGE = 'QUESTION_IMAGE',
  OPTION_IMAGE = 'OPTION_IMAGE',
  FORMULA_RENDER = 'FORMULA_RENDER',
}
